const sampleProducts = [
  {
    name: 'Banarasi Silk Saree',
    sku: 'CSP-BAN-001',
    price: 180.00,
    originalPrice: 240.00,
    currency: 'MYR',
    category: 'Banarasi Silk',
    categories: ['Banarasi Silk', 'Sarees', "Women's Wear"],
    description: 'Exquisite Banarasi silk saree with rich gold zari weaving throughout.',
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=600&q=80',
    images: ['https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=600&q=80'],
    inStock: true,
    stockQuantity: 15,
    status: 'published',
    color: 'Magenta',
    fabric: 'Banarasi Silk',
    occasion: 'Wedding',
    gender: 'Women',
    isNewProduct: true,
    isFeatured: true
  },
  {
    name: 'Kanchipuram Silk Saree',
    sku: 'CSP-KAN-002',
    price: 160.00,
    originalPrice: 210.00,
    currency: 'MYR',
    category: 'Kanchipuram Silk',
    categories: ['Kanchipuram Silk', 'Sarees', "Women's Wear"],
    description: 'Traditional Kanchipuram silk saree with rich pallu and contrasting border.',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80',
    images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80'],
    inStock: true,
    stockQuantity: 20,
    status: 'published',
    color: 'Gold',
    fabric: 'Kanchipuram Silk',
    occasion: 'Festive',
    gender: 'Women',
    isNewProduct: true,
    isFeatured: true
  },
  {
    name: 'Soft Silk Saree',
    sku: 'CSP-SFT-003',
    price: 140.00,
    originalPrice: null,
    currency: 'MYR',
    category: 'Soft Silk',
    categories: ['Soft Silk', 'Sarees', "Women's Wear"],
    description: 'Lightweight soft silk saree designed for pure comfort and modern elegance.',
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=600&q=80',
    images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=600&q=80'],
    inStock: true,
    stockQuantity: 12,
    status: 'published',
    color: 'Pink',
    fabric: 'Soft Silk',
    occasion: 'Casual',
    gender: 'Women',
    isNewProduct: false,
    isFeatured: true
  },
  {
    name: 'Tussar Silk Saree',
    sku: 'CSP-TUS-004',
    price: 190.00,
    originalPrice: 250.00,
    currency: 'MYR',
    category: 'Tussar Silk',
    categories: ['Tussar Silk', 'Sarees', "Women's Wear"],
    description: 'Authentic Tussar silk saree featuring rich textured weave and zari border.',
    image: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=600&q=80',
    images: ['https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=600&q=80'],
    inStock: true,
    stockQuantity: 8,
    status: 'published',
    color: 'Blue',
    fabric: 'Tussar Silk',
    occasion: 'Party Wear',
    gender: 'Women',
    isNewProduct: true,
    isFeatured: false
  },
  {
    name: 'Royal Silk Kurta & Pyjama Set',
    sku: 'CSP-MEN-005',
    price: 155.00,
    originalPrice: 199.00,
    currency: 'MYR',
    category: "Men's Wear",
    categories: ["Men's Wear", 'Kurta Sets'],
    description: 'Elegant handcrafted silk kurta paired with comfortable tailored pyjamas for festive celebrations.',
    image: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=600&q=80',
    images: ['https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=600&q=80'],
    inStock: true,
    stockQuantity: 15,
    status: 'published',
    color: 'Cream Gold',
    fabric: 'Raw Silk',
    occasion: 'Wedding',
    gender: 'Men',
    isNewProduct: true,
    isFeatured: true
  },
  {
    name: 'Kanchipuram Silk Shirt & Dhoti Set',
    sku: 'CSP-MEN-006',
    price: 210.00,
    originalPrice: 270.00,
    currency: 'MYR',
    category: "Men's Wear",
    categories: ["Men's Wear", 'Dhoti Sets', 'Traditional Wear'],
    description: 'Premium pure Kanchipuram silk shirt paired with matching gold zari bordered silk dhoti.',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80',
    images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80'],
    inStock: true,
    stockQuantity: 10,
    status: 'published',
    color: 'Ivory White',
    fabric: 'Pure Silk',
    occasion: 'Wedding',
    gender: 'Men',
    isNewProduct: true,
    isFeatured: true
  },
  {
    name: 'Heritage Silk Shawl & Stole',
    sku: 'CSP-UNI-007',
    price: 85.00,
    originalPrice: 110.00,
    currency: 'MYR',
    category: 'Accessories',
    categories: ['Accessories', 'Unisex'],
    description: 'Versatile pure silk shawl featuring golden zari embroidery suitable for both men and women.',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80',
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80'],
    inStock: true,
    stockQuantity: 25,
    status: 'published',
    color: 'Maroon Gold',
    fabric: 'Silk Blend',
    occasion: 'Festive',
    gender: 'Unisex',
    isNewProduct: false,
    isFeatured: true
  }
];

module.exports = sampleProducts;
